### ISSUE TITLE
Error after upgrade from 3.6 to 4

### ISSUE THREAD

**Issue by dgastudio** [Papooch/nestjs-cls#121]
Cannot create ClsService because no AsyncLocalStorage instance was provided.
Please make sure that ClsService is only provided by the ClsModule and not constructed manually or added to the providers array.

i have checked the mgiration guide, there are no mentions about this

any advice? thank you

**Comment by Papooch** [comment]
You probably see the error because you either put `ClsService` into the `providers` array of some module or you constuct it manually with `new` somewhere.

It is not in the migration guide because it has never been a suported way of registering it in a module. Doing so would result in a runtime error (see https://github.com/Papooch/nestjs-cls/issues/79), therefore I added an explicit check to the constructor to throw an error early in the bootstrap phase.

If you believe you don't use it incorrectly and still get that error, please share a minimal reproduction example so I can investigate.

**Comment by dgastudio** [comment]
@Papooch 
sorry for late response.
yes, you was right, i have used cls cervice inside app module providers
thank you very much!

**Comment by enbits** [comment]
I believe there's some unexpected behavior triggered by this change. I have a standard set up: 

```
//app.module.ts
imports: [
    ClsModule.forRoot({
      middleware: {
        mount: true,
      },
      global: true,
    }),
```

Then if I need to inject it somewhere I import it in the module that contains the class where ClsService will be injected: 

```
//some.module.ts
@Module({
  imports: [PrismaModule, ClsService],
  ....
})
```


```
//some.controller.ts
 constructor(
    private readonly clsService: ClsService,
  ) {}
```

This was working fine in 3.X, but with 4.X I'm getting the same error as dgastudio. I'm not adding it to the providers section nor manually constructing it. Am I doing something wrong?

Thanks

**Comment by Papooch** [comment]
@enbits You're listing `ClsService` in `imports` - that's wrong, only _modules_ should go there.

Replace it with `ClsModule` and it should work as intended.
