### ISSUE TITLE
How to use with extended client?

### ISSUE THREAD

**Issue by darr1s** [Papooch/nestjs-cls#125]
Hi! Thanks for the lib.

The question is as title. I have extended client (available in ts, or as nest service)

**Comment by Papooch** [comment]
Hi, I am not exactly sure which client or library you're referring to, as this GitHub repository is a monorepo with multiple `nestjs-cls` related libs, but from the working, I'm going to assume you're talking about an extended `Prisma` client and the library `@nestjs-cls/transactional-adapter-prisma`.

Unfortunately, it is not (easily) possible to use an extended client (that is, an another type than the one imported from `@prisma/client`) with the prisma adapter. I'm planning to add that option to the library, but for the time being, to achieve what you want, you'll have to [create a custom adapter](https://papooch.github.io/nestjs-cls/plugins/available-plugins/transactional/creating-custom-adapter).

Fortunately, it is not that hard as [the entire source-code of the prisma adapter can be found here](https://github.com/Papooch/nestjs-cls/blob/main/packages/transactional-adapters/transactional-adapter-prisma/src/lib/transactional-adapter-prisma.ts)

And basically the only thing that needs changing is the [import at the very top](https://github.com/Papooch/nestjs-cls/blob/fbb27dc9bbdf5a07c3c0fe9298c2b81f5c5fd29e/packages/transactional-adapters/transactional-adapter-prisma/src/lib/transactional-adapter-prisma.ts#L2)(and the related uses) from `import { PrismaClient } from '@prisma/client'` to `import { MyPrismaClient } from '../my/prisma-client`.

Also please keep in mind, that since the propagated transaction object is the one that gets passed to `prisma.$transaction(( THIS_ONE ) => ...)`, if you use a custom service that extends the PrismaClient with new _class methods_, those won't be available on the transaction object.

**Comment by Papooch** [comment]
It it now possible to use a custom Prisma Client type since `@nestjs-cls/transactional-adapter-prisma` `v1.1.0`. Please see [updated docs](https://papooch.github.io/nestjs-cls/plugins/available-plugins/transactional/prisma-adapter#custom-client-type).
