### ISSUE TITLE
Global middleware not running on Nest > 10.3.2 (fastify, global prefix)

### ISSUE THREAD

**Issue by xtrinch** [Papooch/nestjs-cls#134]
When upgrading nestjs from 10.3.2 to anything above that, my global middleware stops running.

Namely, this middleware:
```
@Module({
  controllers: [AppController],
  providers: [AppService],
  imports: compact([
    ClsModule.forRoot({
      global: true,
      middleware: {
        mount: true,
        setup: (cls: ClsService<ClsStore>, req) => {
          // something -> this does not execute at all in 10.3.4
        },
      },
    }),
...
```

No issues in any of the below versions. Using latest nestjs-cls 4.3.0

Any ideas?

**Comment by Papooch** [comment]
Thanks for reporting, I'll look into it.

Let me ask you some clarifying questions:
* Are you on express or fastify?
* Are you using global prefix (`app.setGlobalPrefix`)?

**Comment by xtrinch** [comment]
Fastify,
global prefix /api

**Comment by Papooch** [comment]
I suspect the "fix" in [this NestJS release](https://github.com/nestjs/nest/releases/tag/v10.3.4) might be the cause.

The `mount` option binds the `ClsMiddleware` to `*`. Could you try creating a custom middleware and mounting it to `*`, too, to see if it gets executed or not? If it does, then it's a bug in this library, otherwise it's a bug in NestJS and needs to be reported.

**Comment by Papooch** [comment]
I have investigated on my side, updated NestJS to `10.3.7` and added many missing tests to the test suite involving Fastify and global prefix, but I was not able to reproduce the issue. All seems to work correctly.

Can I ask you for a minimal reproduction which shows the incorrect behavior?

**Comment by xtrinch** [comment]
Perhaps the title is a bit misleading - the middleware does run (cls service can be injected normally) - it's just the setup function that doesn't get executed

**Comment by Papooch** [comment]
So the context gets initialized, but the _setup_ function is not executed? That's beyond strange, execution of that code is controlled by ClsMiddleware, not Nest.

I tested that yesterday on latest version of everything with a basic console log and it did work.

Are you sure you only updated Nest and not other libraries that might interfere?

Can you share a minimal repro of your issue. I am not sure I'd be able to help you otherwise.

**Comment by xtrinch** [comment]
Sorry, I commented to hastily. I did some more testing, and for me, it turns out no middleware gets executed at all - not even a custom one that I add. I'll try to provide a reproduction repo but at the end of the day I don't think this is an issue with nestjs-cls at all. I might have some mismatched dependencies or something I'm not sure yet

**Comment by Papooch** [comment]
Make sure to also update `@nestjs/platform-fastify` to the latest version, and _do not_ install `fastify`.

**Comment by xtrinch** [comment]
Managed to boil it down to the exclude param of global prefix - opened an issue here https://github.com/nestjs/nest/issues/13401
