### ISSUE TITLE
When generating id for RPC using interceptor I get the whole context instead of "request data"

### ISSUE THREAD

**Issue by micgre0** [Papooch/nestjs-cls#168]
Hi, I have some problem when I try to generate id for RPC using interceptor. The code is as follows:

```ts
idGenerator: (request: any) => {
          
          return request.id || cuid();
        },
```

As i get the context I can't reference id in the way above. I mean, for RPC, I need to check if it's the context, then use `getData()` so I can get request id.

https://github.com/Papooch/nestjs-cls/blob/e93f5506b87643f3bda9fecec782ba398670446b/packages/core/src/lib/cls-initializers/utils/context-cls-store-map.ts#L43-L44

Is this expected behavior? I mean based on documentation 

> By default, the generated ID is a string based on Math.random(), but you can provide a custom function in the idGenerator option.
This function receives the Request (or ExecutionContext in case a ClsGuard is used) as the first parameter, which can be used in the generation process and should return (or resolve with) a string ID that will be stored in the CLS for later use.

**Comment by Papooch** [comment]
That is the correct behavior, since I can't know which part of the execution context you need to generate the ID, I can't just provide the payload alone to the id generator - also, I can't know if you use the interceptor for a HTTP, GQL or a RPC route. That's why in the case of the interceptor of a guard, the entire execution context is passed to the method and you need to extract the part that you need.

(I now see that the mention of the interceptor is missing in the documentation - I need to fix that)

So yes, if you need to get the ID from the payload of a RPC call, you need to use something like:

```ts
  idGenerator: (ctx) => {        
    return ctx.switchToRpc().getData().id ?? cuid();
  },
```
