### ISSUE TITLE
Is there a way to manually eject out of a transaction without raising an error?

### ISSUE THREAD

**Issue by ThomasShih** [Papooch/nestjs-cls#183]
I'm currently using neverthrow to wrap all errors in my codebase. This means that I don't raise any errors and therefore the current implementation (typeorm adapter) won't rollback.

I know that we can do a manual rollback with queryRunner.rollbackTransaction, but I'm not sure how to access that within a request context. 

Assistance would be appreciated!

**Comment by Papooch** [comment]
Hi, the goal of this library is to abstract away transactions, so that the code executing the query doesn't have to care whether it's run within a transaction or not, so while you _could_ access queryRunner through `this.tx.queryRunner?.rollbackTransaction();`, it would throw an error in case there was no transaction,so I would not recommend this approach.

The `nestjs-cls` library doesn't attempt to add any more abstraction over transactions than necessary, so it does the bare minimum to
1) put a transaction manager/reference into the context
2) expose the transaction manager/reference via a typed accessor
3) leave any and all rollback mechanisms of the underlying database libraries _via adapters_.

All the "official" adapters try to be as simple as possible - usually, throwing an error within a `transaction` callback rolls back the transaction, so the implementation of the TypeORM (and most other) adapter is essentially just [these few lines](https://github.com/Papooch/nestjs-cls/blob/74bcec38ea99041ba852fc4d7b08f138d682d136/packages/transactional-adapters/transactional-adapter-typeorm/src/lib/transactional-adapter-typeorm.ts#L40):

```ts
optionsFactory = (dataSource: DataSource) => ({
    wrapWithTransaction: async (
        options: TypeOrmTransactionOptions,
        fn: (...args: any[]) => Promise<any>,
        setClient: (client?: EntityManager) => void,
    ) => {
        return dataSource.transaction(options?.isolationLevel, (trx) => {
            setClient(trx); // store transaction in the CLS
            return fn(); // execute the decorated function
                         // if this throws, the transaction is automatically rolled back by TypeORM
        });
    },
    getFallbackInstance: () => dataSource.manager,
});
```

So, for your use-case, I would recommend solving it at the adapter level by writing a **custom result-aware adapter** by extending the `TransactionalAdapterTypeOrm` and overriding `optionsFactory` with something like the following: 

```diff
optionsFactory = (dataSource: DataSource) => ({
    wrapWithTransaction: async (
        options: TypeOrmTransactionOptions,
        fn: (...args: any[]) => Promise<any>,
        setClient: (client?: EntityManager) => void,
    ) => {
-       return dataSource.transaction(options?.isolationLevel, (trx) => {
+       return dataSource.transaction(options?.isolationLevel, async (trx) => {
            setClient(trx);
-           return fn()
+           const result = await fn();
+           if (result.isErr()) {
+               await trx.queryRunner?.rollbackTransaction()
+           }
+           return result
        });
    },
    getFallbackInstance: () => dataSource.manager,
});
```

(you'll probably want to wrap `rollbackTransaction` in a result, too, since it can potentially throw)

This should ensure that any time a method decorated with `@Transactional()` returns a result of `Err`, the transaction rolls back and the original result is returned.

**Comment by ThomasShih** [comment]
Thank you!

We have tried both implementations already and neither seems to be the smartest thing to do. 

Our use of neverthrow contain errors that may not want to be handled, and may just be a logical decision making step, we can state that all `.isErr() === true` returns at the transaction level must be hard "ejects, handle like throws", but that seems like a way too overly broad statement to assume with a broad stroke.

The `tx.queryRunner?.rollbackTransaction()` is an option using the built in adaptor, we can write a generic function to verify the transaction exists, and rollback only if. But it seems that there is a check missing from the lib because calling rollbackTransaction means that no transaction exist, and if we don't throw an error the lib still attempts a commit afterwards:

1. Transaction starts by lib
2. some logic
3. custom rollback triggered
4. some logic
5. Transaction attempts to be stopped by lib.

**Comment by Papooch** [comment]
Ah, I see, that is the nature of the callback-style transaction, in which the only way to rollback is to throw an error.

In that case, you could write an adapter with [manual transaction control](https://papooch.github.io/nestjs-cls/plugins/available-plugins/transactional).

Like this:
```ts
wrapWithTransaction: async (
    options: TypeOrmTransactionOptions,
    fn: (...args: any[]) => Promise<any>,
    setClient: (client?: EntityManager) => void,
) => {
    const queryRunner = dataSource.createQueryRunner()
    try {
        await queryRunner.connect()
        setClient(queryRunner.manager)
        const result = await fn()
        if(result.isErr()) {
            await queryRunner.rollbackTransaction()
        } else {
            await queryRunner.commitTransaction()
        }
        return result;
    } catch (e) {
        await queryRunner.rollbackTransaction()
        return err( /*...*/ )
    } finally {
        await queryRunner.release()
    }
}
```
This way the transaction not committed if `Err` is returner.

But if you'd like to explicitly rollback the transaction within the wrapped function, then I'm afraid you can't use this library without inventing a hacky solution.
