### ISSUE TITLE
CLS not active in a NestJS Hybrid RPC interceptor test

### ISSUE THREAD

**Issue by keymatch-clovis** [Papooch/nestjs-cls#187]
Firstly, thank you for creating this amazing piece of software!

I'm trying to create some tests for a hybrid NestJS application using interceptors and the CLS module. My tests look something like this:

```typescript
let app: INestApplication;
let client: ClientProxy;
let cls: ClsService;

beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
        imports: [
            ClsModule,
            ClientsModule.register([ /*...*/ ]),
        ],
        controllers: [TestController],
    }).compile();

    app = moduleRef.createNestApplication();
    app.connectMicroservice<MicroserviceOptions>({ /*...*/ });

    await app.startAllMicroservices();
    await app.init();

    client = app.get<ClientProxy>("TEST_CLIENT");
    cls = app.get(ClsService);
});
```

This is a basic configuration for what I think it's a hybrid application. After this, I just create some tests like:

```typescript 
it("Interceptor works", async () => {
    await cls.run(async () => {
        await supertest(app.getHttpServer())
            .post("/test?test=123")
            .send({
                test: 1234,
                testing: "tester",
            })
            .set({ "x-tracking-id": "1234" })
            .expect("test");
    });
});

it("Log with microservices works", async () => {
    await cls.run(async () => {
        const record = new RmqRecordBuilder("test")
            .setOptions({
                headers: {
                    "x-tracking-id": "aoeu",
                },
            })
            .build();

        const result = await firstValueFrom(
            client.send({ cmd: "testing" }, record),
        );
        console.log(result);
    });
});
```

What I'm trying to achieve is that, when I send some information in the `headers` object of the request, I can extract it, and then add it to the CLS context. For this, I use a test controller like:

```typescript
@Controller()
@UseInterceptors(TrackingIdInterceptor, LogInterceptor)
class TestController {
    @Post("test")
    post(@Body() test: unknown) {
        return "test";
    }

    @MessagePattern({ cmd: "testing" })
    pattern() {
        return "testing";
    }
}
```

The `TrackingIdInterceptor` gets the tracking ID from the headers and adds it to the CLS context, and the `LogInterceptor` just takes that ID and logs it.

Now, the problem I'm experiencing is that the `cls.run` function only seems to activate the CLS context when using the HTTP method, and not the RPC method; the logic I have in both interceptors look something like:

```typescript
@Injectable()
export class TrackingIdInterceptor implements NestInterceptor {
    constructor(private readonly cls: ClsService) {}

    intercept(
        context: ExecutionContext,
        next: CallHandler,
    ): Observable<unknown> {
        // ...
        if (this.cls && this.cls.isActive()) {
            // Do stuff...
        } else {
            new Logger().error("CLS not set or not found!");
        }

        return next.handle();
    }
}
```

Here, when the context type is HTTP, everything works fine, but when it's RPC it's defined, but not active.

One solution I found is adding the `ClsInterceptor` to the controller (as this issue talks about: #91), and everything works fine. The problem with that is that any property set in the tests with `cls.run` or `cls.runWith` is lost. And I have to declare the `ClsModule` as global.

I seem to very much lack the brain power or expertise to understand what is happening. Have you found something similar? Am I using the project in a wrong way?

Thank you so much!

------

#### Versions used:
 - @nestjs: 10.4.6
 - nestjs-cls: 4.4.1
 - vitest: 2.1.4

**Comment by Papooch** [comment]
Multiple issues here.

## 1) You are entering the CLS context on the wrong side

You are testing your app via _controller_, which is an _entry point_ into your application. That means, some other client application (web client/gateway) is going to call these endpoints.

In this scenario, the client it is the test case code.

In a normal scenario, the request travels _serialized_ over network, so you can't expect that any CLS context will be preserved.

Yet, you are wrapping the request _on the caller's (client's) side_. The only reason this might seem to work is because the request happens in-process and does not travel over any network, which is a side effect of how Jest works, _but this is not what happens in reality_.

The request should be wrapped in a CLS context on the application's side and only then populated with the header values.

That means, yes, you should include `ClsModule.forRoot(...)` in your test module.

## 2) You are mixing RPC methods and HTTP methods in a single controller

This is not really advised, since you can't be entirely sure which configuration applies to where (for example, RPC controllers, ignore the controller prefix `@Controller("path")`). There are also issues with how enhancers are bound in cases of Hybrid Apps.

## 3) Hybrid apps don't automatically inherit global enhancers

If you use `ClsModule.forRoot({ interceptor: { mount: true } })` _in a hybrid app_, you will notice that the interceptor only works for HTTP and not for RPC. To make it work for both, you either need to put `@UseInterceptors(ClsInterceptor)` on top of the RPC controller, or explicitly [tell it to inherit the configuration](https://docs.nestjs.com/faq/hybrid-application#sharing-configuration) in the connect microservice call.

**Comment by keymatch-clovis** [comment]
Thank you so much for taking some time to answer my question, I really appreciate it.

You have helped me a lot, I understand now what's wrong. I'll take your recommendations and change how the controllers are working. Fortunately, this is all testing and to see everything is working sort of fine.

What I've done is use a custom interceptor in the test module, like:

```typescript
const moduleRef = await Test.createTestingModule({
    // ...
    providers: [
        {
            provide: "APP_INTERCEPTOR",
            useValue: {
                intercept: (_: ExecutionContext, next: CallHandler) => {
                    cls.enter();
                    return next.handle();
                },
            },
        },
    ],
    // ...
}).compile();
```

And now everything works as I understand it has to.

> 1) You are entering the CLS context on the wrong side

This really opened my eyes, I hadn't noticed that. Thank you! This was really the key piece of understanding that I was lacking.
