### ISSUE TITLE
Adding ClsModule as an interceptor is not working

### ISSUE THREAD

**Issue by jaligamap** [Papooch/nestjs-cls#91]
I have two services, one exposes REST apis and the other one grpc apis. I was able to successfully add the ClsModule as a middleware for the first one but not able to do it with the second one. I can see that the interceptor is initialized properly when the app starts up with this message
```
[Nest] 28817  - 10/23/2023, 6:56:34 PM   DEBUG [ClsModule] ClsInterceptor will be automatically mounted
```
But, in my controller, when I access the ClsService, I get this error
```
[Nest] 28817  - 10/23/2023, 6:56:37 PM   ERROR [RpcExceptionsHandler] Cannot set the key "key". No CLS context available, please make sure that a ClsMiddleware/Guard/Interceptor has set up the context, or wrap any calls that depend on CLS with "ClsService#run"
```

This is what i added to the app.module
```ts
ClsModule.forRoot({
      interceptor: {
        mount: true,
        setup: (cls, context) => {
          const req = context.getArgs();
          console.log(`request is ${req}`);
          cls.set('TENANT_ID', 'tenant');
        },
      },
    }),
```

**Comment by Papooch** [comment]
Hi, thanks for thr bug report. 

Is the second service a **hybrid** one or just pure microserivce created with `NestFactory.createMicroservice`? If the former, then global interceptors are not automatically bound to microservice routes (only to HTTP routes) and you have to explicitly bind them to the controller with `@UseInterceptors(ClsInterceptor)`.

Also, to be fair, I haven't tested the library with gRPC explicitly, since Nest interceptors should work in a transport agnostic way, so if the suggestion above doesn't work, would you mind creating a reproducible example where I could debug this locally?

**Comment by jaligamap** [comment]
Thank you. I tried binding it to the controller and now I get this error.
Error: Nest can't resolve dependencies of the ClsInterceptor (?). Please make sure that the argument ClsInterceptorOptions at index [0] is available in the ApprovalRequestsModule context.

**Comment by Papooch** [comment]
You might need to make the ClsModule global, so the options provider is available in the module:
```diff
 ClsModule.forRoot({
+  global: true
   interceptor: {
     mount: true,
     setup: (cls, context) => {
       const req = context.getArgs();
       console.log(`request is ${req}`);
       cls.set('TENANT_ID', 'tenant');
     },
   },
 }),
```

Alternatively, you can register the `ClsModule.forRoot()` in the module where you use that interceptor, or configure it in a wrapper module and use [Module re-exporting](https://docs.nestjs.com/modules#module-re-exporting) to make all the module's providers available in consumer modules, too.

**Comment by jaligamap** [comment]
Awesome. Looks like adding the globalflag and binding it to the controller, worked.

**Comment by Papooch** [comment]
Cool, I'm glad it worked!
