### ISSUE TITLE
How to store DB transaction object that is available only within a callback?

### ISSUE THREAD

**Issue by sam-artuso** [Papooch/nestjs-cls#98]
Some DB libraries manage a DB transaction within a callback.

Here's an example of what Sequelize calls a "managed transaction":
```ts
await sequelize.transaction(async (t) => {
  // queries in here can use `t` 
});
```

Heres' another (very similar) example with `pg-promise`:
```ts
await db.tx(t => { /* ... */ })
```

The advantage is that the commit or rollback are automatic based on whether an error is thrown within the callback.

I'm having a hard time figuring out how to store `t` in AsyncLocalStorage globally. My sense is that I should use an interceptor, but I'm not sure how?

**Comment by Papooch** [comment]
In short, basically the same way [you did here](https://github.com/Papooch/nestjs-cls/issues/97#issuecomment-1897520819). But you also need to make sure to remove the transaction object from the context once the transaction finishes.

This can be done in two ways:
1) Re-use the same CLS-context
```ts
// if we're in a nested transaction, remember the previous one
const prevTx = cls.get('transaction')
// wrap the call in managed transaction
await db.tx(async t => {
  try {
     cls.set('transaction', t)
     return await someService.doStuff()
  } finally {
     // make sure to replace the transaction with the original value
     // otherwise it will be accessible even after the transaction is complete
     // which will cause errors in case you attempt to re-use it
     cls.set('transaction', prevTx)
  }
})
```

2) Create a nested CLS-context around the call
```ts
// make sure to inherit the existing context, otherwise it will be empty
cls.run({ ifNested: 'inherit' }, async () => {
   return db.tx(async t => {
      // this sets the transaction on the nested context only
      cls.set('transaction', t)
      return await someService.doStuff()
   })
})
```
The latter one has the nice property that CLS-enabled transactions will work even if no context was initialized prior.

> Note: Sequelize supports [CLS-enabled transactions out of the box](https://sequelize.org/docs/v6/other-topics/transactions/#automatically-pass-transactions-to-all-queries)

**Comment by sam-artuso** [comment]
I'm not sure I made myself clear. My question is how to link an HTTP request to a fresh db transaction:

```ts
    ClsModule.forRoot({
      global: true,
      middleware: {
        mount: true,
        setup: (cls, req) => ???,
      },
    }),
``` 

P.S.: this is for an HTTP context, not a "CLI" context like in [this other question of mine](https://github.com/Papooch/nestjs-cls/issues/97).

**Comment by Papooch** [comment]
I see, well, if you want to wrap the _entire request_ with a transaction, which I *would not* recommend for the reasons listed below (*), you cannot do it via the `ClsMiddleware` setup. That function is there only to populate the context, but you can't further wrap the execution of the flow. For that, you'd need to create a custom middleware or interceptor that wraps the `next()` (or `handle.next()`) call with what I shared earlier (replacing `someService.doStuff()` with the `next` call).

(*) Since wrapping code with transaction effectively _executes_ the transaction at the database level, it is advised to only start it when you absolutely need it as close to the actual database calls as possible. If you implicitly wrap each request, then you'll end up with an empty transaction a lot of times, in case the request flow never makes it to the database call, or you'll be unnecessarily locking the database for simple `SELECT` queries.

**Comment by sam-artuso** [comment]
Yes, it's true, my approach would create a lot of empty transactions and has overhead. Still, [some people](https://docs.djangoproject.com/en/5.0/topics/db/transactions/#tying-transactions-to-http-requests) do it because it's simple.

Do you have any suggestions on how to create a decorator that I can just drop at the point closest to where I need the transaction to start?

**Comment by Papooch** [comment]
Please see the [`@nestjs-cls/transactional`](https://papooch.github.io/nestjs-cls/plugins/available-plugins/transactional) plugin.
